### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by ghost** [rizualam/list_word#1]
1. Why is gets used when you are accepting input from command line arguments
2. why is the count initialized with 1 and Not 0?
3. Why did you use while loop, instead of for?
   Because this is a typical case for "for" loop, (initialization, comparison and increment)

**Comment by rizualam** [comment]
#include <stdio.h>
int main(int argc, char *argv[])
{
    char a[100];
    int i=0,count=0;
    printf("enter the sentence\n");
    gets(a);
    if(a[i]=='\0')
    {
        count=0;
    }
    else{
        for(i=0;a[i]='\0';i++)
        {
            if (a[i]==' '|| a[i]=='\0')
            {
                count++;
            }
        }
    } 
    printf("no.of words in sentence=%d",count);
    return 0;
}

**Comment by rizualam** [comment]
#include <stdio.h>
#include <string.h>
int main(int argc, char *argv[])
{
    int count=0,i;
    char ch[200];
    if (argc <= 1)
    {
        return 0;
    }
    for(i=1;i<=argc;i++)
    {
        strcat(ch,argv[i]);
        if(argc>1)
        {
            strcat(ch," ");
        }
    }
    strcat(ch,"\0");
    if(ch[i]=='\0')
    {
        count=0;
    }
    else{
for(i=0;ch[i]='\0';i++)
{
if (ch[i]==' '|| ch[i]=='\0')
{
count++;
}
}
}
    printf("no.of words in sentence=%d",count);
    return 0;
}

**Comment by ghost** [comment]
sounds good
